// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('v4 monday', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    // await driver.quit();
  })
  it('v4 monday', async function() {
    await driver.get("http://localhost:8080/")
    await driver.manage().window().setRect(1920, 1080)
    await driver.findElement(By.css(".md-alignment-centered > .md-tabs-navigation > .md-button:nth-child(2) .md-button-content")).click()
    await driver.findElement(By.xpath("//div[2]/div/div/div/div/a[2]/div/div")).click()
  })
})
